name: tests

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3]
        laravel: [^6.0, ^7.0, ^8.0, ^9.0, ^10.0]
        exclude:
          - php: 7.2
            laravel: ^8.0
          - php: 7.2
            laravel: ^9.0
          - php: 7.2
            laravel: ^10.0
          - php: 7.3
            laravel: ^9.0
          - php: 7.3
            laravel: ^10.0
          - php: 7.4
            laravel: ^9.0
          - php: 7.4
            laravel: ^10.0
          - php: 8.0
            laravel: ^10.0
          - php: 8.1
            laravel: ^6.0
          - php: 8.1
            laravel: ^7.0
          - php: 8.2
            laravel: ^7.0
          - php: 8.2
            laravel: ^6.0
          - php: 8.3
            laravel: ^7.0
          - php: 8.3
            laravel: ^6.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php }}
              extensions: mbstring, exif, iconv, tokenizer
              coverage: none

        - name: Install dependencies
          run: |
              composer require "laravel/framework=${{ matrix.laravel }}" --no-update
              composer update --prefer-dist --no-interaction --no-progress
        - name: Execute tests
          run: ./vendor/bin/phpunit
